# Generated by Django 5.2.10 on 2026-02-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
